dist: bionic
language: python
install:
  - sudo apt-get install dh-python
  - pip install tox-travis
  - pip install codecov
matrix:
  include:
    - python: 3.6
      env: ENV=pep8,py3
    - python: 3.7
      env: ENV=pep8,py3
    - python: 3.8
      env: ENV=pep8,py3
script: tox -c tox.ini -e $ENV
after_success:
  - codecov --verbose --gcov-glob unit_tests/*
