#!/usr/bin/env python3
#
# Push new stable branch to origin
# (requires projects file with list of projects, one name per line)
#
# Example: pkg-push-branches ./projects stable/victoria
#

import argparse
import os
import subprocess

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("projects", help="Path to projects file")
    parser.add_argument("branch", help="Branch name to push")
    args = parser.parse_args()

    with open(args.projects, "r") as f:
        for line in f.readlines():
            project = line.rstrip()
            print("Processing project: {}".format(project))
            saved_path = os.getcwd()
            os.chdir(project)
            cmd = ['git', 'checkout', args.branch]
            subprocess.check_call(cmd)
            cmd = ['git', 'push', '--set-upstream', 'origin', args.branch]
            subprocess.check_call(cmd)
            os.chdir(saved_path)

if __name__ == "__main__":
    main()
