#!/usr/bin/env python3
#
# Check if stable branch exists
# (requires projects file with list of projects, one name per line)
#
# Example: pkg-check-stable-branches ~/src/scripts/packaging/projects stable/victoria
#

import argparse
import subprocess

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("projects", help="Path to projects file")
    parser.add_argument("branch", help="Stable branch name to check")
    args = parser.parse_args()

    projs = args.projects
    with open(projs, 'r') as f, open('yes', 'w') as yes, open('no', 'w') as no:
        for line in f.readlines():
            project = line.rstrip()
            cmd = ['pkg-check-stable-branch', project, args.branch]
            if subprocess.call(cmd) == 0:
                yes.write("{}".format(line))
            else:
                no.write("{}".format(line))


if __name__ == "__main__":
    main()
