#!/usr/bin/env python3
#
# Create stable branches for several projects
# (requires projects file with list of projects, one name per line)
#
# Example: pkg-create-stable-branches ~/src/scripts/pkg-scripts/projects stable/victoria
#

import argparse
import subprocess

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("projects", help="Path to projects file")
    parser.add_argument("branch", help="Stable branch name to create")
    args = parser.parse_args()

    with open(args.projects, "r") as f:
        for line in f.readlines():
            project = line.rstrip()
            cmd = ['pkg-create-stable-branch', project, args.branch]
            try:
                subprocess.check_call(cmd)
            except subprocess.CalledProcessError:
                continue

if __name__ == "__main__":
    main()
