#!/bin/bash
#
# Update common files such as .launchpad.yaml and gbp.conf for the
# specified package.
#
# Example: pkg-sync-common-files cinder master caracal
# Example: pkg-sync-common-files cinder stable/2023.2 bobcat
#

set -ex

if [ $# -ne 3 ]; then
    echo "Usage: $0 package-name branch-name openstack-codename"
    echo "       $0 cinder master bobcat"
    echo "       $0 cinder stable/antelope antelope"
    exit
fi

package_name=$1
branch_name=$2
openstack_codename=$3

if [ ! -d ./cloud-archive-tools ]; then
    git clone lp:~ubuntu-cloud-archive/+git/cloud-archive-tools
else
    cd cloud-archive-tools
    git pull
    cd -
fi

git clone lp:~ubuntu-openstack-dev/ubuntu/+source/${package_name} || true
cd ${package_name}

git checkout ${branch_name}
cp ../cloud-archive-tools/cloud_global/${openstack_codename}/.launchpad.yaml .
git add .launchpad.yaml
cp ../cloud-archive-tools/cloud_global/${openstack_codename}/gbp.conf ./debian/
git add ./debian/gbp.conf

if [[ "stable/bobcat" =~ "stable" ]]; then
    dch "d/gbp.conf, .launchpad.yaml: Sync from cloud-archive-tools for ${openstack_codename}."
else
    dch -n "d/gbp.conf, .launchpad.yaml: Sync from cloud-archive-tools for ${openstack_codename}."
fi
sed -i "/  \* Non-maintainer upload./d" "debian/changelog"

debcommit -a
